In [8]:
import pandas as pd
csv1 = pd.read_csv("D:\\Python\\Pandas\\tut5c.csv")
csv1
csv1.index   # Returns starting and ending of index
csv1.columns # Returns all the columns head
csv1.describe() # Returns mean, minimum, maximum etc. values
csv1.head()   #Returns 5 rows from top
csv1.head(2)   #Returns 2 rows from top
csv1.tail()   #Returns 5 rows from bottom
csv1.tail(2)   #Returns 2 rows from bottom
csv1[2:5]  # Returns from index 2 to index 4 rows
csv1.index.array  # Returns indexes in array
csv1.to_numpy()  # Returns rows in numpy array format

array([['ELECTHERM', 'ELECTROTHERM LIMITED', 473907, 486468, 654],
       ['NBIFIN', 'N.B.I. INDUSTRIAL FINANCE COMPANY', 5754, 46546546,
        65],
       ['HINDCON', 'HINDSON CHEMICALS LIMITED', 32564894, 6546546, 5959],
       ['GKWLMITED', 'GKW LIMITED', 666543, 444, 3],
       ['21STCENMGM', '21ST CENTURY MANAGEMRNT SERVICE', 23154949, 4,
        654],
       ['ALPHAGEO', 'ALPHAGEO LIMITED', 987987987, 4864, 5],
       ['UNIENTER', 'UNIPHOS ENTERPRISES LIMITED', 46479, 4, 52591],
       ['JAGSNPHARM', 'JAGSONPAL PHARMACEUTICALS LIMITED', 4489498, 64,
        48962],
       ['SKMEGGPROD', 'SKM ENGG PRODUCTRS EXPORT LIMITED', 47979887, 4,
        83],
       ['SWELECTES', 'SWELECT ENERGY SYSTEMS LIMITED', 94894987, 654, 83],
       ['NAHARPOLY', 'NAHERPOLY FILMS LIMITED', 46464, 4, 8],
       ['PODDARHOUS', 'PODDAR HOUSINGU AND DEVELOPMENT', 4894897987, 4,
        648],
       ['LINC', 'LINC LOMITED', 46549877, 46, 651],
       ['SHIVAMILLS', 'SHIVA MILLS LIMITED', 7444896, 489, 5]],
      dtype=object)

In [25]:
import numpy as np
v = np.asarray(csv1)   #Retruns row in array format
# print(v)
csv1.sort_index(axis = 0, ascending= False)  # Sort the rows in decending index number

# To change a particular element -> csv.loc[row, column] = value
csv1.loc[0, 'SYMBOL']= 'Python'
# print(csv1)

# To get paricular data -> csv.loc[[row], [column]]
csv1.loc[[4,5], ['SYMBOL', 'SECURITY']]

# To get all data of some paricular rows or columns we use ':'
csv1.loc[[4,5], :]

# To get a particular data -> csv.iloc[row, column]
csv1.iloc[2,2]

# To drop a paticular row or column -> csv.drop(row/column, axis = 0/1)
csv1.drop("SECURITY", axis = 1)

        SYMBOL  TODAY-VOLUME  AVG. VOLUME  CHANGE
0       Python        473907       486468     654
1       NBIFIN          5754     46546546      65
2      HINDCON      32564894      6546546    5959
3    GKWLMITED        666543          444       3
4   21STCENMGM      23154949            4     654
5     ALPHAGEO     987987987         4864       5
6     UNIENTER         46479            4   52591
7   JAGSNPHARM       4489498           64   48962
8   SKMEGGPROD      47979887            4      83
9    SWELECTES      94894987          654      83
10   NAHARPOLY         46464            4       8
11  PODDARHOUS    4894897987            4     648
12        LINC      46549877           46     651
13  SHIVAMILLS       7444896          489       5